# Generated by Django 6.0.5 on 2026-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='JustClick', max_length=100)),
                ('site_tagline', models.CharField(default='Shop Smarter, Order via WhatsApp', max_length=255)),
                ('whatsapp_number', models.CharField(default='1234567890', help_text='Business WhatsApp phone number', max_length=20)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
    ]
