# Generated by Django 6.0.5 on 2026-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='hero_banner',
            field=models.ImageField(blank=True, help_text='Upload custom hero banner image (fallback to default generated image if empty)', null=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='hero_subtitle',
            field=models.TextField(default='Quality products, best prices and fast delivery. Just choose and order on WhatsApp!'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='hero_title',
            field=models.CharField(default='Shop Smart.<br>Order Instantly via <span>WhatsApp</span>', help_text='HTML tags like <span> are allowed for styling', max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload custom store logo (fallback to default SVG logo if empty)', null=True, upload_to='store/'),
        ),
    ]
