# Generated by Django 6.0.5 on 2026-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeconfiguration_hero_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this product in the Featured Products section on the homepage'),
        ),
    ]
