# Generated by Django 6.0.5 on 2026-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfiguration',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload custom store logo. For best styling, please upload a small image with a height around 32px to 40px, ideally a transparent PNG/SVG (fallback to default SVG logo if empty)', null=True, upload_to='store/'),
        ),
    ]
